name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            features: tiletopia-core/draco,tiletopia-store/gcs,tiletopia-store/azure
          - os: macos-14
            features: tiletopia-core/draco,tiletopia-store/gcs,tiletopia-store/azure
          - os: windows-2022
            features: tiletopia-core/draco,tiletopia-store/gcs,tiletopia-store/azure
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --features ${{ matrix.features }}

      - name: Test
        run: cargo test --release --features ${{ matrix.features }}

      - name: Clippy
        run: cargo clippy --features ${{ matrix.features }} -- -D warnings

  fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --check
